package(default_visibility = ["//visibility:public"])

exports_files(glob(
    ["**"],
    exclude = ["BUILD.bazel"],
))

filegroup(
    name = "pack_files",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
)

# --- bazel_repo_srcs (managed by tools/bazel/repo_tree.py) ---

filegroup(
    name = "bazel_repo_srcs",
    srcs = glob(
        ["**"],
        allow_empty = True,
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
