// Command gen-client generates the typed Go API client from the live
// OpenAPI spec.
//
// Pipeline:
//  1. Fetch the 3.0-downgrade spec directly from a SupervisorMux built
//     against an empty resolver. Huma v2 emits the downgrade
//     automatically; oapi-codegen v2.6.0 consumes it cleanly where it
//     chokes on 3.1. The supervisor owns every operation, so one fetch
//     yields the entire API surface — no merge step.
//  2. Pipe the spec unchanged to oapi-codegen. There is NO preprocessing.
//     The routes we register ARE the routes we expose. Every schema and
//     path in the generated client matches what the server publishes to
//     external consumers — no hidden rename, no hidden path rewrite.
//     skip-prune keeps documentation-only compatibility components
//     available to in-tree callers that still deserialize those shapes.
//  3. Replace oapi-codegen's "Code generated by <module> version <v>"
//     line with a fixed header. That line reports how the oapi-codegen
//     binary was built (go install embeds module info; a Bazel build of
//     the same pinned version does not), not anything about the output,
//     so normalizing it keeps the committed client byte-identical across
//     both build paths.
//  4. Write the generated client to stdout.
//
// Usage:
//
//	go run ./cmd/gen-client [-oapi-codegen PATH] > internal/api/genclient/client_gen.go
//
// -oapi-codegen names the oapi-codegen binary to run. Without it gen-client
// uses the oapi-codegen on PATH, or else `go run`s oapiCodegenModule at
// oapiCodegenVersion, the version MODULE.bazel pins for the hermetic build
// and `make install-oapi-codegen` installs.
//
// Or via go:generate in internal/api/genclient/doc.go. A CI drift test
// regenerates the client and diffs against the committed file so the
// spec is the source of truth.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"regexp"
	"slices"
	"time"

	"github.com/gastownhall/gascity/internal/api"
)

// generatedHeader replaces oapi-codegen's build-identity header line.
const generatedHeader = "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 via cmd/gen-client. DO NOT EDIT."

var oapiCodegenHeader = regexp.MustCompile(`(?m)^// Code generated by .* DO NOT EDIT\.$`)

const (
	oapiCodegenModule  = "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen"
	oapiCodegenVersion = "v2.6.0"
)

func main() {
	oapiCodegen := flag.String("oapi-codegen", "", "oapi-codegen binary to run (default: oapi-codegen on PATH, else go run "+oapiCodegenModule+"@"+oapiCodegenVersion+")")
	flag.Parse()
	if err := run(oapiCodegenCommand(*oapiCodegen, exec.LookPath)); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// oapiCodegenCommand returns the argv prefix that runs oapi-codegen: the
// explicit binary, else the one on PATH, else `go run` of the pinned version.
func oapiCodegenCommand(explicit string, lookPath func(string) (string, error)) []string {
	if explicit != "" {
		return []string{explicit}
	}
	if bin, err := lookPath("oapi-codegen"); err == nil {
		return []string{bin}
	}
	return []string{"go", "run", oapiCodegenModule + "@" + oapiCodegenVersion}
}

func run(oapiCodegen []string) error {
	// Step 1: fetch the 3.0-downgraded spec from the supervisor.
	sm := api.NewSupervisorMux(emptyResolver{}, nil, false, "", "", time.Time{})
	req := httptest.NewRequest(http.MethodGet, "/openapi-3.0.json", nil)
	rec := httptest.NewRecorder()
	sm.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		return fmt.Errorf("GET /openapi-3.0.json returned %d: %s", rec.Code, rec.Body.String())
	}

	// Step 2: write the spec verbatim to a temp file for oapi-codegen.
	tmp, err := os.CreateTemp("", "gc-openapi-3.0-*.json")
	if err != nil {
		return fmt.Errorf("tempfile: %w", err)
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.Write(rec.Body.Bytes()); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp spec: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp spec: %w", err)
	}

	// Step 3: invoke oapi-codegen. Output goes to stdout — the caller
	// redirects it to internal/api/genclient/client_gen.go.
	var generated bytes.Buffer
	args := slices.Concat(oapiCodegen[1:], []string{"-generate", "types,client,skip-prune", "-package", "genclient", tmp.Name()})
	cmd := exec.Command(oapiCodegen[0], args...)
	cmd.Stdout = &generated
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("oapi-codegen: %w", err)
	}
	out, err := canonicalizeGeneratedHeader(generated.Bytes())
	if err != nil {
		return err
	}
	if _, err := os.Stdout.Write(out); err != nil {
		return fmt.Errorf("write client: %w", err)
	}
	return nil
}

// canonicalizeGeneratedHeader replaces the single oapi-codegen
// "Code generated by ... DO NOT EDIT." line with generatedHeader.
func canonicalizeGeneratedHeader(src []byte) ([]byte, error) {
	if n := len(oapiCodegenHeader.FindAllIndex(src, -1)); n != 1 {
		return nil, fmt.Errorf("oapi-codegen output has %d generated-code header lines, want exactly 1", n)
	}
	return oapiCodegenHeader.ReplaceAllLiteral(src, []byte(generatedHeader)), nil
}

// emptyResolver implements api.CityResolver with no cities. Schema
// generation is reflection-based and never calls resolver methods.
type emptyResolver struct{}

func (emptyResolver) ListCities() []api.CityInfo   { return nil }
func (emptyResolver) CityState(_ string) api.State { return nil }
