package main

import (
	"errors"
	"slices"
	"strings"
	"testing"
)

func TestOapiCodegenCommandPrefersExplicitThenPathThenPinnedGoRun(t *testing.T) {
	onPath := func(string) (string, error) { return "/usr/bin/oapi-codegen", nil }
	missing := func(string) (string, error) { return "", errors.New("not found") }
	for _, tc := range []struct {
		name     string
		explicit string
		lookPath func(string) (string, error)
		want     []string
	}{
		{name: "explicit", explicit: "/bazel/oapi-codegen", lookPath: onPath, want: []string{"/bazel/oapi-codegen"}},
		{name: "path", lookPath: onPath, want: []string{"/usr/bin/oapi-codegen"}},
		{name: "pinned go run", lookPath: missing, want: []string{"go", "run", "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := oapiCodegenCommand(tc.explicit, tc.lookPath); !slices.Equal(got, tc.want) {
				t.Fatalf("oapiCodegenCommand = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestCanonicalizeGeneratedHeaderDropsToolBuildIdentity(t *testing.T) {
	for _, tc := range []struct {
		name   string
		header string
	}{
		{name: "go install build", header: "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT."},
		{name: "bazel build without module info", header: "// Code generated by unknown module path version unknown version DO NOT EDIT."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			in := "// Package genclient provides primitives.\n//\n" + tc.header + "\npackage genclient\n"
			got, err := canonicalizeGeneratedHeader([]byte(in))
			if err != nil {
				t.Fatalf("canonicalizeGeneratedHeader: %v", err)
			}
			want := "// Package genclient provides primitives.\n//\n" + generatedHeader + "\npackage genclient\n"
			if string(got) != want {
				t.Fatalf("got:\n%s\nwant:\n%s", got, want)
			}
		})
	}
}

func TestCanonicalizeGeneratedHeaderRejectsMissingOrDuplicateHeader(t *testing.T) {
	line := "// Code generated by x version y DO NOT EDIT.\n"
	for _, in := range []string{"package genclient\n", line + line + "package genclient\n"} {
		if _, err := canonicalizeGeneratedHeader([]byte(in)); err == nil {
			t.Errorf("canonicalizeGeneratedHeader(%q) succeeded, want error", in)
		}
	}
}

func TestGeneratedHeaderIsRecognizedAsGeneratedCode(t *testing.T) {
	if !strings.HasPrefix(generatedHeader, "// Code generated ") || !strings.HasSuffix(generatedHeader, " DO NOT EDIT.") {
		t.Fatalf("generatedHeader %q does not match the Go generated-code convention", generatedHeader)
	}
}
