load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "docsync_test",
    srcs = [
        "connected_clients_test.go",
        "docsync_test.go",
        "testenv_import_test.go",
    ],
    data = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ) + [
        "//:go.mod",
        "//:repo_source_tree",
        "//contrib:all_files",
        "//docs:all_files",
    ],
    deps = [
        "//internal/bazeltest",
        "//internal/docgen",
        "//internal/testenv",
    ],
)

# --- bazel_repo_srcs (managed by tools/bazel/repo_tree.py) ---

filegroup(
    name = "bazel_repo_srcs",
    srcs = glob(
        ["**"],
        allow_empty = True,
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
