load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "worker_inference_test",
    srcs = ["testenv_import_test.go"],
    deps = ["//internal/testenv"],
)

# --- bazel_repo_srcs (managed by tools/bazel/repo_tree.py) ---

filegroup(
    name = "bazel_repo_srcs",
    srcs = glob(
        ["**"],
        allow_empty = True,
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
